### PR TITLE
update field name from zeek site

### PR DESCRIPTION
**Pull request by frack113**
When check sigma rule find a diff ("_" rather than ".").
Fix name according to the reference https://docs.zeek.org/en/v4.1.1/logs/x509.html
Some field name are not in the reference.

### CODE REVIEW

**Comment by Cyb3rWard0g** [comment]
Thank you very much @frack113 ! :)

**Comment by Cyb3rWard0g** [comment]
Hello @neu5ron ! Would you mind sharing your thoughts on this? I believe it was done this way for a reason? Is this part of the pipeline that you have not merged yet? Whenever you have some time 🙏🏾  thank you !

**Comment by frack113** [comment]
Hi,
for sigma rule, I have check [rdp.yml](https://github.com/OTRF/OSSEM-DD/blob/main/zeek/network-protocols/events/rdp.yml) that have the field name in `name` with "." .

**Comment by neu5ron** [comment]
looks ok, sometimes zeek is output to nest as _ or .'s 
doesn't really matter. LGTM

**Pull request merged**
