### PR TITLE
Added New ETW Events (Windows 11)

### PR DESCRIPTION
**Pull request by nasbench**
This PR adds new ETW events that were added in Windows 11. The list of ETW providers that has been added is the following:

- Microsoft-Windows-Kernel-Cache
- Microsoft-Windows-Kernel-Dump
- Microsoft-Windows-TenantRestrictions
- Microsoft-Windows-USB-USB4DeviceRouter-EventLogs
- Microsoft-Windows-WerKernel
- Microsoft-Windows-WinHttp-Pca
- Microsoft-Windows-WinINet-Pca
- Microsoft-Windows-Winsock-Sockets
- Microsoft-Windows-ZTraceMaps

The following additions are based on the following research:

- [ETW Resources Project](https://github.com/nasbench/ETW-Resources/tree/main/ETW%20Events%20List/Markdown/W10_21H1)
- [Windows 11 “New” ETW Providers — Overview](https://nasbench.medium.com/windows-11-new-etw-providers-overview-a2a5fbc85775)

### CODE REVIEW

**Comment by Cyb3rWard0g** [comment]
Wow! That's awesome @nasbench ! Thank you very much for sharing your research through the OSSEM project as well 🙏🏾  I would love to know how we can improve the tracking of those ETW providers in the future. The versioning, new fields, etc. Any feedback would be appreciated 😄

**Comment by Cyb3rWard0g** [comment]
Great suggestion @nasbench ! mmm I assume we would have to go through all the releases docs. Does that exist somewhere? I remember downloading a few lists of events in a word document from MS docs and it had some of that information. I was wondering if you knew of any specific resources. I will also ask internally.

**Comment by AndrewRathbun** [comment]
@nasbench we could do a diff between each version of Windows and include tables of what changed from 1803 to 1809 to 1903 etc, from A-Z for every version we're already working on. Server, too. That's at least ultimately what I had in mind for our ongoing project 😎

**Comment by nasbench** [comment]
That's exactly what I was about to suggest @AndrewRathbun 

Using the different manifests we've been collecting and diffing them, will yield us great results and will give us a lot of insights into when were new events and providers added.

@Cyb3rWard0g We've been dumping ETW manifests from the different versions of Windows (See [ETW Manifests](https://github.com/nasbench/ETW-Resources/tree/main/ETW%20Providers%20Manifests)) So we could use this as a very good basis for what we're talking about here.

**Pull request merged**
